[tool.ruff]
# Modern, fast Python linter (replaces flake8, isort, and more)
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
]
ignore = [
    "E501",  # line too long (handled by black)
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # unused imports in __init__.py
"tests/*" = ["ARG", "S101"]  # Allow unused args and assert in tests

[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | venv
  | build
  | dist
  | alembic/versions
)/
'''

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # Start lenient, gradually enforce
ignore_missing_imports = true  # For libraries without type stubs
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]

# Pydantic plugin configuration
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

# SQLAlchemy models - disable plugin's strict checking for legacy declarative style
[[tool.mypy.overrides]]
module = "app.models.*"
disable_error_code = ["assignment", "attr-defined", "misc"]

# Repositories interact heavily with SQLAlchemy's dynamic attributes
[[tool.mypy.overrides]]
module = "app.repositories.*"
disable_error_code = ["assignment", "attr-defined", "override"]

# Controllers interact with models and perform assignments
[[tool.mypy.overrides]]
module = "app.controllers.*"
disable_error_code = ["assignment", "arg-type"]

# API layer does FastAPI automatic ORM->Pydantic conversion
[[tool.mypy.overrides]]
module = "app.api.*"
disable_error_code = ["return-value", "arg-type", "misc", "assignment"]

[tool.pytest.ini_options]
# Keep pytest config here instead of pytest.ini (modern approach)
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
